### PR TITLE
add navigation bar.

### PR DESCRIPTION
**Pull request by wangj97**
add navigation bar. when app launch, show login screen. after clicked the button, show HomeScreen and navigation bar on the bottom.

### CODE REVIEW

**Review by pachia-lee — COMMENTED** [review]
Instructor quiz will only be visible during a live quiz, so it doesn't have to be apart of the tabs.

**Comment by pachia-lee** [comment]
Also, once user is logged in, we don't need to login button and create acc anymore, so you might have to create a seperate screen for that. Just have the same things as home screen except for those two buttons.

**Review by pachia-lee — APPROVED** [review]
This should be okay now.

**Review by skogmanpe40 — APPROVED** [review]
Everything looks good

**Pull request merged**
